sql/backup_schedule.sql
=> RMAN Backup duplicated

sql/psu-1.sql, sql/psu-2.sql
=> Fix output psu not expected 

README.md
=> Travis Build Unknown

config.json, config/config.go, fetch/oratab, main.go
=> Added oratab param in config.json

fetch/addm, fetch/backup, fetch/db, fetch/dbmounted, fetch/dbstatus, fetch/dbversion, fetch/feature, fetch/license, fetch/oratab, fetch/patch, fetch/psu, fetch/schema, fetch/segmentadvisor, fetch/stats, fetch/tablespace, main.go, marshal/oratab.go, model/oratab.go
=> Changed fetchers to use ORACLE_HOME from args

fetch/oratab
Fixes https://github.com/ercole-io/ercole-server/issues/50
=> Fixed oratab exit status

main.go
Fixed https://github.com/ercole-io/ercole-server/issues/49
=> Added bug active dataguard 2311894.1 detection

sql/db.sql
Fixes https://github.com/ercole-io/ercole-agent/issues/43
=> Fixed db.sql lines number

.travis.yml
=> Fixed version replacing in .travis.yml

sql/addm.sql
=>  fetch/addm seems to be broken on OEL 7.4 / Oracle db 11.2.0.4 #40

main.go
Fixes https://github.com/ercole-io/ercole-agent/issues/61
=> Added active guard error ORA-01555 detection

fetch/dbstatus
Fixes https://github.com/ercole-io/ercole-agent/issues/65
=> Added pmon presence check

package/rhel7/60-ercole-agent.preset, package/rhel7/ercole-agent.spec
Fixes https://github.com/ercole-io/ercole-server/issues/61
=> Added ercole-agent preset file for rhel7

package/rhel6/ercole-agent.spec
Fixes https://github.com/ercole-io/ercole-server/issues/24
=> rhel6 enable service at startup

fetch/host, fetch/win.ps1, model/host.go
Fixes https://github.com/ercole-io/ercole-server/issues/97
=> Added AixCluster

fetch/win.ps1
=> Fixed win.ps1

builder/builder.go, builder/fetcher.go, config.json, config/config.go, go.mod, go.sum, main.go, marshal/oratab.go, utils/routine.go
=> Parallelize requests

builder/builder.go
=> Fix null databases returned

fetch/mssqlserver/ercoleAgentMsSQLServer-Gather.ps1, sql/mssqlserver/mssqlserver.backup_schedule.sql
backup scheduler convert hour to varchar for a better output in json
service status
=> mssqlserver bug fixing

.travis.yml, Makefile, builder/common_builder/common_builder.go, builder/common_builder/databases.go, builder/common_builder/exadata.go, builder/common_builder/virtualization.go, config.json, config/config.go, fetch/linux/exadata/info.sh, fetch/linux/exadata/storage-status.sh, fetcher/cmd_lnx.go, fetcher/cmd_win.go, fetcher/common_fetcher.go, fetcher/fetcher.go, fetcher/linux_fetcher.go, fetcher/windows_fetcher.go, marshal/exadata_cell_disks.go, marshal/exadata_devices.go, model/exadata.go, model/exadata_cell_disk.go, model/exadata_device.go, model/extrainfo.go, package/rhel5/ercole-agent.spec, package/rhel6/ercole-agent.spec, package/rhel7/ercole-agent.spec, package/rhel8/ercole-agent.spec, utils/utils.go
=> Added exadata fetcher

.travis.yml
=> Fixes #158

.travis.yml
=> Added tests in travis

builder/common_builder/oracle_databases.go, fetch/linux/oracle_running_databases.sh, fetcher/fetcher.go, fetcher/linux_fetcher.go, fetcher/windows_fetcher.go, go.mod, go.sum, package/rhel5/ercole-agent.spec, package/rhel6/ercole-agent.spec, package/rhel7/ercole-agent.spec, package/rhel8/ercole-agent.spec
=> Added UnlistedRunningDatabase fetcher

builder/common_builder/oracle_databases.go, config.json, fetcher/fetcher.go, fetcher/linux_fetcher.go, fetcher/windows_fetcher.go, go.mod, go.sum, main.go, marshal/oracle/listpdb.go, sql/checkpdb.sql, sql/listpdb.sql
=> Added support to pdbs

fetch/win.ps1
=> Removed wrong comma

agentmodel/microsoft.go, builder/common_builder/common_builder.go, builder/common_builder/microsoft_sqlserver.go, config.json, config/config.go, fetch/windows/ercoleAgentMsSQLServer-Gather.ps1, fetcher/fetcher.go, fetcher/linux_fetcher.go, fetcher/windows_fetcher.go, go.mod, go.sum, marshal/microsoft/backup_schedule.go, marshal/microsoft/dbmounted.go, marshal/microsoft/edition.go, marshal/microsoft/features.go, marshal/microsoft/licensing_info.go, marshal/microsoft/listdatabases.go, marshal/microsoft/listinstances.go, marshal/microsoft/patches.go, marshal/microsoft/schema.go, marshal/microsoft/tablespace.go, package/win/installer.nsi, sql/mssqlserver/mssqlserver.edition.sql
=> [WIP] Added support to MSSQL server

fetcher/windows_fetcher.go
=> Fixed GetOracleDatabaseOpenDb

marshal/oracle/segment_advisors.go, marshal/oracle/segment_advisors_test.go, sql/segment_advisor.sql
=> Fixed segment advisor fetcher and marshaller

fetch/linux/oratab.sh
=> Fixed oratab.sh

builder/common_builder/virtualization.go, fetch/linux/oratab.sh, marshal/vms.go
=> Removed not_in_cluster fix

marshal/oracle/database.go, marshal/oracle/database_test.go
=> Check correct value for Archivelog returned value

.gitignore, .travis.yml, Makefile, builder/common_builder/oracle_databases.go, builder/common_builder/oracle_databases_test.go, go.mod, go.sum
=> Fix wrong unlisted running db

go.mod, go.sum, main.go
=> Add timeout handling for connection to server

config/config.go
=> Add check that config.Period is > 0 else set default

marshal/common.go, marshal/common_test.go, marshal/oracle/database.go
=> Parse float64 even if with comma

.agola/config.jsonnet, go.mod, go.sum, main.go
=> Log response body

config/check_directory.go, config/check_directory_windows.go, config/config.go, go.mod, go.sum, logger/logger.go, logger/logrus_logger.go
There was an useless check that the current user was the owner of the directory.
This wasn't needed, only write and execute permission bits are.
=> Fixed check directory is writable

builder/common_builder/oracle_databases.go, builder/common_builder/virtualization.go
=> Fix parallelized cluster info collection

fetch/linux/host.sh, fetch/linux/license.sh
=> Added hardwareAbstractionTechnology KVM

builder/common_builder/common_builder.go, builder/common_builder/microsoft_sqlserver.go, builder/common_builder/mysql.go, builder/common_builder/oracle_databases.go, builder/common_builder/oracle_databases_test.go, builder/common_builder/virtualization.go, config.json, fetcher/fetcher.go, fetcher/linux_fetcher.go, fetcher/windows_fetcher.go, main.go, marshal/cluster_membership_status.go, marshal/cluster_membership_status_test.go, marshal/oracle/database_feature_usage_stat.go
=> Manage fetchers errors to continue if not critical

fetch/linux/license.sh, sql/license.sql
=> Fix license fetcher

sql/license.sql, sql/opt.sql
Fix #271 Update script to check licenses
=> Update script to check licenses

main.go
Fix #141 Check server with a ping at start
=> Check server with a ping at start

builder/common_builder/oracle_databases.go, fetch/linux/services.sh, fetch/windows/win.ps1, fetcher/fetcher.go, fetcher/linux_fetcher.go, fetcher/windows_fetcher.go, go.mod, go.sum, marshal/common.go, marshal/oracle/services.go, package/rhel6/ercole-agent.spec, package/rhel7/ercole-agent.spec, package/rhel8/ercole-agent.spec, sql/services.sql
Fix [#355 Add Oracle Services](https://github.com/ercole-io/ercole/issues/355)
=> Add Oracle Services

fetch/linux/cloud_membership_aws.sh
Improved for https://github.com/ercole-io/ercole/issues/662
=> Improved fetcher script

go.mod, go.sum, main.go
=> Delay agent start

fetcher/cmd_lnx.go, fetcher/cmd_win.go, fetcher/linux_fetcher.go, fetcher/windows_fetcher.go
=> 286: added filesystem command timeout

sql/backup_schedule.sql
Fix #289 Increase backup_schedule.sql line size
=> Increase backup_schedule.sql line size

builder/common_builder/common_builder.go, builder/common_builder/virtualization.go, config.json, config/config.go, go.mod, go.sum
Fix #291 Interface with Oracle Virtualization Engine
=> Interface with Oracle Virtualization Engine

builder/common_builder/oracle_databases.go
=> Detect connection error

config/config.go, go.mod, go.sum
=> Read more configuration.json files

config/config.go, main.go
Fix #306 Panic while reading configs
=> Panic while reading configs

fetcher/fetcher.go, fetcher/linux_fetcher.go, fetcher/windows_fetcher.go
=> Added deadline to fetcher executions

builder/common_builder/oracle_databases.go
=> Managed fetcher errors

builder/common_builder/oracle_databases.go
Fix #295 Ignore errors from fetcher service
=> Ignore errors from fetcher service

builder/common_builder/oracle_databases.go
=> Can't get PDB [DOCUTEST] tablespaces

builder/common_builder/oracle_databases.go
=> Fix Can't get PDB tablespaces

builder/common_builder/common_builder.go, builder/common_builder/oracle_databases.go, builder/common_builder/oracle_databases_test.go
=> Added check for duplicated oratab entries

builder/common_builder/oracle_databases.go
=> Fix channel size

marshal/common.go, marshal/common_test.go, marshal/oracle/tablespaces.go
=> Accept comma marshalling tablespaces

builder/common_builder/oracle_databases.go, marshal/common.go, marshal/common_test.go, marshal/oracle/tablespaces.go
=> Various fixes

builder/common_builder/mysql.go
=> Removed MySQL UUID error

fetch/linux/license.sh, fetch/linux/opt.sh, fetch/windows/win.ps1, package/rhel6/ercole-agent.spec, package/rhel7/ercole-agent.spec, package/rhel8/ercole-agent.spec, sql/license_pluggable.sql, sql/opt_pluggable.sql, sql/pluggable.sql
Fix #331 Change PDM management
=> Change PDM management

sql/license.sql, sql/license_pluggable.sql
=> Add exception in sql query if a DB is free

config.json, config/config.go, fetch/linux/mysql/mysql_gather.sh, fetcher/linux_fetcher.go
Fix #337 Add mysql port as configuration parameter
=> Add mysql port as configuration parameter

builder/common_builder/oracle_databases.go, fetch/linux/dbstatus.sh, marshal/oracle/database_test.go, sql/db.sql, sql/dbstatus.sql
=> Get open-mode

sql/dbmounted.sql
=> Fix dbmounted.sql

cmd/serve.go
=> 366 remove colon from temp hostdata

builder/common_builder/oracle_databases.go, marshal/oracle/patches.go, marshal/oracle/patches_test.go
=> 266 check date strings patches

builder/common_builder/mysql.go, fetch/linux/mysql/mysql_gather.sh, fetcher/fetcher.go, fetcher/linux_fetcher.go, fetcher/windows_fetcher.go, marshal/mysql/old_instance.go, marshal/mysql/old_instance_test.go, marshal/mysql/version.go, package/rhel6/ercole-agent.spec, package/rhel7/ercole-agent.spec, package/rhel8/ercole-agent.spec, sql/mysql/old_instance.sql, sql/mysql/version.sql
Fix #335 Update mysql fetcher for release less than 5.7
=> Update mysql fetcher for release less than 5.7

builder/common_builder/mysql.go, fetch/linux/mysql/mysql_gather.sh
Fix #359 In mysql_gather changed path to call sql script
=> In mysql_gather changed path to call sql script

sql/mysql/instance.sql
Fix #361 Modify version management in MySql
=> Modify version management in MySql

marshal/mysql/old_instance.go
Fix #365 Mysql read-only-log-enabled is equal to test
=> Mysql read-only-log-enabled is equal to test

package/rhel6/ercole-agent
Resolve #329 In rhel6 agent version file log is created everytime and not updated
=> In rhel6 agent version file log is created everytime and not updated

.agola/config.jsonnet
Resolve #375 Push assets to github on release
=> Push assets to github on release

fetch/windows/win.ps1
Resolve # 379 Add oVirt management in Windows agent
=> Add oVirt management in Windows agent

.agola/config.jsonnet, builder/common_builder/oracle_databases.go, go.mod, go.sum
Resolve #391 Add grant management also for Oracle pdb databases
=> Add grant management also for Oracle pdb databases

.agola/config.jsonnet, package/deb/control, package/deb/preinst
=> Added deb build

go.mod, go.sum, marshal/postgresql/database.go, marshal/postgresql/database_test.go, marshal/postgresql/instance.go, marshal/postgresql/instance_test.go, marshal/postgresql/schema.go, marshal/postgresql/schema_test.go, marshal/postgresql/setting.go, marshal/postgresql/setting_test.go, sql/postgresql/d_info.sql, sql/postgresql/d_info_v10.sql, sql/postgresql/i_info_v10.sql, sql/postgresql/i_settings.sql, sql/postgresql/n_info.sql, sql/postgresql/n_info_v10.sql
=> Updated psql fetchers

.agola/config.jsonnet, builder/common_builder/postgresql_databases.go, fetch/linux/cloud_membership_aws.sh, fetch/linux/cluster_membership_status.sh, fetch/linux/host.sh, fetch/linux/postgresql/psql.sh
=> WIP: Fixed deb installation

.agola/config.jsonnet, package/deb/postinst
=> Added system service & logrotation

config.json
=> Fixed config verbose

go.mod, go.sum, marshal/oracle/services.go, sql/services.sql
Resolve #345 Remove oracle database service creation date field
=> Remove oracle database service creation date field

marshal/oracle/exadata_components.go
=> Fixed exadata release date marshal

cmd/serve.go, go.mod, go.sum
Resolve #419 Use hostdata period for FreshnessCheckJob
=> Use hostdata period for FreshnessCheckJob

fetch/windows/win.ps1
Resolve #186 Windows installation must be in C:\ErcoleAgent
=> Windows installation must be in C:\ErcoleAgent

cmd/check_oratab.go, fetch/linux/suggest_oratab.sh, package/rhel6/ercole-agent.spec, package/rhel7/ercole-agent.spec, package/rhel8/ercole-agent.spec
=> Added oratab helper command

builder/common_builder/oracle_databases.go
=> Ignore pdb data if status is mounted

builder/common_builder/virtualization.go
=> Fixed total cores

builder/common_builder/virtualization.go, go.mod, go.sum
Resolve #435 OLVM add physical server model name
=> OLVM add physical server model name

sql/schema.sql, sql/schema_pdb.sql
sql part of [Retrieve schemas status from Oracle Database#431](https://github.com/ercole-io/ercole-agent/issues/431)
=> Add field account status

go.mod, go.sum, marshal/oracle/schemas.go, sql/schema.sql, sql/schema_pdb.sql
Resolve #431 Retrieve schemas status from Oracle Database
=> Retrieve schemas status from Oracle Database

go.mod, go.sum, marshal/oracle/services.go
=> Refactored FailoverDelay

fetch/linux/suggest_oratab.sh
Resolve #452 Checking the oratab on the agent adding the commented entries
=> Checking the oratab on the agent adding the commented entries

builder/common_builder/common_builder.go, builder/common_builder/mongodb_databases.go, config.json, config/config.go, go.mod, go.sum
Resolve #456 Add support to MongoDB
=> Add support to MongoDB

config.json
Changed config.json in MongoDB section
=> Changed config.json in MongoDB section

fetch/windows/ercoleAgentMsSQLServer-Gather.ps1
=> Updated win fetcher

fetch/windows/win.ps1
=> Fixed location in win fetcher

builder/common_builder/oracle_databases.go, fetch/linux/cdb_cpu_iops.sh, fetch/linux/pdb_cpu_iops.sh, fetcher/fetcher.go, fetcher/linux_fetcher.go, fetcher/windows_fetcher.go, go.mod, go.sum, marshal/oracle/storage_provisionings.go, marshal/oracle/storage_provisionings_test.go, package/rhel6/ercole-agent.spec, package/rhel7/ercole-agent.spec, package/rhel8/ercole-agent.spec, sql/cdb_cpu_iops.sql, sql/pdb_cpu_iops.sql
=> Added IOPS fetcher for oracle db & pdb

builder/common_builder/common_builder.go, fetch/linux/sar_cpu_only_linux.sh, fetcher/fetcher.go, fetcher/linux_fetcher.go, fetcher/windows_fetcher.go, go.mod, go.sum, marshal/consumption.go, marshal/consumption_test.go, marshal/oracle/common.go, marshal/oracle/storage_provisionings.go, package/rhel6/ercole-agent.spec, package/rhel7/ercole-agent.spec, package/rhel8/ercole-agent.spec
=> Added host CPU consumption fetcher

fetch/linux/sar_cpu_only_linux.sh, marshal/oracle/storage_provisionings.go, marshal/oracle/storage_provisionings_pdb.go
=> Ignored unmarked output in storage provisioning

sql/opt.sql, sql/opt_pluggable.sql
=> Updated opt queries

builder/builder.go, builder/common_builder/common_builder.go
=> Improved exadata hostname

builder/common_builder/oracle_databases.go, fetch/linux/to_postgresql.sh, fetch/linux/to_postgresql_pluggable.sh, fetcher/fetcher.go, fetcher/linux_fetcher.go, fetcher/windows_fetcher.go, go.mod, go.sum, marshal/oracle/postgres_migrability.go, marshal/oracle/postgres_migrability_test.go, package/rhel6/ercole-agent.spec, package/rhel7/ercole-agent.spec, package/rhel8/ercole-agent.spec, sql/to_postgresql.sql
=> Added oracle db & pdb migrability to pgsql

fetch/linux/exadata/new_info.sh, fetcher/linux_fetcher.go
=> Added user param & hostID to exadata script

builder/builder.go, go.mod, go.sum, marshal/oracle/exadata_instance.go, marshal/oracle/exadata_instance_test.go
=> Added hostid to exadata components

package/rhel7/ercole-agent.spec, package/rhel8/ercole-agent.spec
=> no overwrite ercole-agent.service

.agola/config.jsonnet, package/rhel9/60-ercole-agent.preset, package/rhel9/ercole-agent.service, package/rhel9/ercole-agent.spec
=> Added rhel9 support

builder/common_builder/mysql.go, config.json, config/config.go, fetch/linux/mysql/mysql_gather.sh, fetcher/fetcher.go, fetcher/linux_fetcher.go, fetcher/windows_fetcher.go
=> Improved mysql config & script

cmd/check_oratab.go
=> Fixed check-oratab cmd

config/config.go, fetch/linux/mysql/mysql_gather.sh
=> Update mysql configuration

fetch/linux/host.sh, go.mod, go.sum, marshal/host.go, marshal/host_test.go
=> Added ClusterWareVersion on host fetcher

builder/common_builder/oracle_databases.go, go.mod, go.sum
=> Added unretrieved database on oracle

cmd/serve.go, config/config.go, package/deb/preinst, package/rhel6/ercole-agent.spec, package/rhel7/ercole-agent.spec, package/rhel8/ercole-agent.spec, package/rhel9/ercole-agent.spec
=> Fixed deb pkg & old config.json

sql/license_pluggable.sql
=> Updated license_pluggable.sql

fetch/linux/suggest_oratab.sh
=> Fixed RAC ONE node issue

fetch/linux/memory_pga_sga_advisory.sh, sql/memory_pga_sga_advisory.sql
Oracle memory, sga, pga advisory suggestions
=> Oracle memory, sga, pga advisory suggestions

builder/common_builder/mongodb_databases.go
=> Provided fetcher compatibility until mongodb:3.6

builder/common_builder/common_builder.go, fetch/linux/cwversion.sh, fetch/linux/host.sh, fetcher/fetcher.go, fetcher/linux_fetcher.go, fetcher/windows_fetcher.go, marshal/cwversion.go, marshal/cwversion_test.go, marshal/host_test.go, package/rhel6/ercole-agent.spec, package/rhel7/ercole-agent.spec, package/rhel8/ercole-agent.spec, package/rhel9/ercole-agent.spec
=> Added new cwversion fetcher

builder/common_builder/oracle_databases.go
Resolve #620 
Commented the unlisted running db function and added to missing dbs only the ones that are listed as pmon services but the agent is unable to retrieve
=> Ignored unlisteddb & updated missing running dbs

builder/common_builder/common_builder.go
Resolve https://github.com/ercole-io/ercole/issues/1824
=> Removed cluster veritas hijacked

builder/common_builder/oracle_databases.go, config.json, config/config.go, fetch/linux/oracle_running_database_home_oratabless.sh, fetch/linux/oracle_running_databases_oratabless.sh, fetcher/fetcher.go, fetcher/linux_fetcher.go, fetcher/windows_fetcher.go, marshal/oracle/oracle_entry.go, marshal/oracle/oracle_entry_test.go, marshal/oracle/pmon_instance_test.go, marshal/oracle/pmon_instances.go, package/rhel6/ercole-agent.spec, package/rhel7/ercole-agent.spec, package/rhel8/ercole-agent.spec, package/rhel9/ercole-agent.spec
=> Added oratab less

builder/common_builder/oracle_databases.go, fetcher/fetcher.go, fetcher/linux_fetcher.go, fetcher/windows_fetcher.go, go.mod, go.sum, marshal/oracle/sizepdb.go, marshal/oracle/sizepdb_test.go, sql/size_pdb.sql
=> Added PGA & SGA to oracle pdb fetcher

cmd/serve.go
=> Forced retryLimit to 1

marshal/oracle/memory_advisor.go, marshal/oracle/memory_advisor_test.go
=> Added three decimals to oracle memory advisor fields

builder/common_builder/oracle_databases.go
=> Improved db segment advisor
